### ISSUE TITLE
Persist element positions

### ISSUE THREAD

**Issue by jmlane** [jmlane/force-deployment#5]
Once a force has been deployed, we will want to persist each elements' position to use as a seed for future initializations.

**Comment by jmlane** [comment]
@Diffusion9 Any thoughts on how to store the seed data across mission/server restarts?

**Comment by Diffusion9** [comment]
Create an array with whatever data you need.
If you want to adhere to existing - loose - standards call it "ASG_*something*"
use `profileNamespace setVariable ["_var",_value]` to send your data to the `profileNamespace`

Eventually `saveProfilenamespace` gets run, the existing data gets saved, and then can be loaded from that namespace on the next reload. Since it's profile data it's stored with the Server's profile. You'll basically have to write your own stuff for saving and loading the data.

I was intending that we use [fn_scheduledStateSave.sqf](https://github.com/AthenaSecurityGroup/Sandbox.Altis/blob/master/functions/persistence/fn_scheduledStateSave.sqf) to run all of the persistence-related saving loops, and after all the saving was done it would run the final `saveProfileNamespace` (which it currently does not do). As it stands right now the `saveProfileNamespace` happens within [fn_saveBaseData.sqf](https://github.com/AthenaSecurityGroup/Sandbox.Altis/blob/master/functions/persistence/fn_saveBaseData.sqf) which is a product of-the-time. It would be good to semi-centralize it. It is also best-practice to limit writes to the `profileNamespace` when possible because it's more disk-intensive, as I understand it.
